# basic options
title: The University of Texas at Arlington - Eta Kappa Nu
author: UTA HKN
email: utahkn@gmail.com
description: Eta Kappa Nu, Epsilon Mu Chapter, Est. 1965
Find us at Nedderman Hall, Room 132
github_username:  utahkn

# Build settings
markdown: kramdown
theme: minima
